"use strict";

// Bundled voice pack manifest.
// Regenerate with: npm run voice-pack:generate
window.DOTA_ENEMY_CD_VOICE_PACK = {
  files: {
    "Aeon Disk": "voice-pack/audio/aeon-disk-ready.wav",
    "Arena of Blood": "voice-pack/audio/arena-of-blood-ready.wav",
    "Astral Imprisonment": "voice-pack/audio/astral-imprisonment-ready.wav",
    "Avalanche": "voice-pack/audio/avalanche-ready.wav",
    "Battle Trance": "voice-pack/audio/battle-trance-ready.wav",
    "Berserker's Call": "voice-pack/audio/berserkers-call-ready.wav",
    "Black Hole": "voice-pack/audio/black-hole-ready.wav",
    "Black King Bar": "voice-pack/audio/black-king-bar-ready.wav",
    "Blast Off!": "voice-pack/audio/blast-off-ready.wav",
    "Bloodstone": "voice-pack/audio/bloodstone-ready.wav",
    "Borrowed Time": "voice-pack/audio/borrowed-time-ready.wav",
    "Burrowstrike": "voice-pack/audio/burrowstrike-ready.wav",
    "Buyback": "voice-pack/audio/buyback-ready.wav",
    "Call Down": "voice-pack/audio/call-down-ready.wav",
    "Cataclysm": "voice-pack/audio/cataclysm-ready.wav",
    "Chain Frost": "voice-pack/audio/chain-frost-ready.wav",
    "Chakram": "voice-pack/audio/chakram-ready.wav",
    "Chaotic Offering": "voice-pack/audio/chaotic-offering-ready.wav",
    "Chronosphere": "voice-pack/audio/chronosphere-ready.wav",
    "Cold Embrace": "voice-pack/audio/cold-embrace-ready.wav",
    "Cooldown": "voice-pack/audio/cooldown-ready.wav",
    "Cursed Crown": "voice-pack/audio/cursed-crown-ready.wav",
    "Dark Ascension": "voice-pack/audio/dark-ascension-ready.wav",
    "Death Ward": "voice-pack/audio/death-ward-ready.wav",
    "Demonic Purge": "voice-pack/audio/demonic-purge-ready.wav",
    "Dismember": "voice-pack/audio/dismember-ready.wav",
    "Disruption": "voice-pack/audio/disruption-ready.wav",
    "Dissimilate": "voice-pack/audio/dissimilate-ready.wav",
    "Doom": "voice-pack/audio/doom-ready.wav",
    "Doppelganger": "voice-pack/audio/doppelganger-ready.wav",
    "Dream Coil": "voice-pack/audio/dream-coil-ready.wav",
    "Duel": "voice-pack/audio/duel-ready.wav",
    "Earth Splitter": "voice-pack/audio/earth-splitter-ready.wav",
    "Echo Slam": "voice-pack/audio/echo-slam-ready.wav",
    "Eclipse": "voice-pack/audio/eclipse-ready.wav",
    "Elder Dragon Form": "voice-pack/audio/elder-dragon-form-ready.wav",
    "Electric Vortex": "voice-pack/audio/electric-vortex-ready.wav",
    "Enrage": "voice-pack/audio/enrage-ready.wav",
    "Epicenter": "voice-pack/audio/epicenter-ready.wav",
    "Exorcism": "voice-pack/audio/exorcism-ready.wav",
    "False Promise": "voice-pack/audio/false-promise-ready.wav",
    "Fiend's Gate": "voice-pack/audio/fiends-gate-ready.wav",
    "Fiend's Grip": "voice-pack/audio/fiends-grip-ready.wav",
    "Finger of Death": "voice-pack/audio/finger-of-death-ready.wav",
    "Fissure": "voice-pack/audio/fissure-ready.wav",
    "Flaming Lasso": "voice-pack/audio/flaming-lasso-ready.wav",
    "Focus Fire": "voice-pack/audio/focus-fire-ready.wav",
    "Freezing Field": "voice-pack/audio/freezing-field-ready.wav",
    "Ghostship": "voice-pack/audio/ghostship-ready.wav",
    "Glimpse": "voice-pack/audio/glimpse-ready.wav",
    "Global Silence": "voice-pack/audio/global-silence-ready.wav",
    "God's Strength": "voice-pack/audio/gods-strength-ready.wav",
    "Guardian Angel": "voice-pack/audio/guardian-angel-ready.wav",
    "Haunt": "voice-pack/audio/haunt-ready.wav",
    "Hex": "voice-pack/audio/hex-ready.wav",
    "Icarus Dive": "voice-pack/audio/icarus-dive-ready.wav",
    "Ice Blast": "voice-pack/audio/ice-blast-ready.wav",
    "Insatiable Hunger": "voice-pack/audio/insatiable-hunger-ready.wav",
    "Laguna Blade": "voice-pack/audio/laguna-blade-ready.wav",
    "Living Armor": "voice-pack/audio/living-armor-ready.wav",
    "Macropyre": "voice-pack/audio/macropyre-ready.wav",
    "Magnetize": "voice-pack/audio/magnetize-ready.wav",
    "Mana Void": "voice-pack/audio/mana-void-ready.wav",
    "Mass Serpent Ward": "voice-pack/audio/mass-serpent-ward-ready.wav",
    "Metamorphosis": "voice-pack/audio/metamorphosis-ready.wav",
    "Moonlight Shadow": "voice-pack/audio/moonlight-shadow-ready.wav",
    "Mortimer Kisses": "voice-pack/audio/mortimer-kisses-ready.wav",
    "Nether Strike": "voice-pack/audio/nether-strike-ready.wav",
    "Nether Swap": "voice-pack/audio/nether-swap-ready.wav",
    "New Spell": "voice-pack/audio/new-spell-ready.wav",
    "Nimbus": "voice-pack/audio/nimbus-ready.wav",
    "Omnislash": "voice-pack/audio/omnislash-ready.wav",
    "Overgrowth": "voice-pack/audio/overgrowth-ready.wav",
    "Phantasm": "voice-pack/audio/phantasm-ready.wav",
    "Phase Shift": "voice-pack/audio/phase-shift-ready.wav",
    "Pierce the Veil": "voice-pack/audio/pierce-the-veil-ready.wav",
    "Primal Roar": "voice-pack/audio/primal-roar-ready.wav",
    "Primal Split": "voice-pack/audio/primal-split-ready.wav",
    "Rage": "voice-pack/audio/rage-ready.wav",
    "Ravage": "voice-pack/audio/ravage-ready.wav",
    "Reaper's Scythe": "voice-pack/audio/reapers-scythe-ready.wav",
    "Refraction": "voice-pack/audio/refraction-ready.wav",
    "Refresher Orb": "voice-pack/audio/refresher-orb-ready.wav",
    "Reincarnation": "voice-pack/audio/reincarnation-ready.wav",
    "Requiem of Souls": "voice-pack/audio/requiem-of-souls-ready.wav",
    "Reverse Polarity": "voice-pack/audio/reverse-polarity-ready.wav",
    "Rolling Thunder": "voice-pack/audio/rolling-thunder-ready.wav",
    "Sanity's Eclipse": "voice-pack/audio/sanitys-eclipse-ready.wav",
    "Shadow Dance": "voice-pack/audio/shadow-dance-ready.wav",
    "Shallow Grave": "voice-pack/audio/shallow-grave-ready.wav",
    "Sharpshooter": "voice-pack/audio/sharpshooter-ready.wav",
    "Sleight of Fist": "voice-pack/audio/sleight-of-fist-ready.wav",
    "Smoke Screen": "voice-pack/audio/smoke-screen-ready.wav",
    "Snowball": "voice-pack/audio/snowball-ready.wav",
    "Song of the Siren": "voice-pack/audio/song-of-the-siren-ready.wav",
    "Sonic Wave": "voice-pack/audio/sonic-wave-ready.wav",
    "Soulbind": "voice-pack/audio/soulbind-ready.wav",
    "Spell Steal": "voice-pack/audio/spell-steal-ready.wav",
    "Spiked Carapace": "voice-pack/audio/spiked-carapace-ready.wav",
    "Stampede": "voice-pack/audio/stampede-ready.wav",
    "Static Storm": "voice-pack/audio/static-storm-ready.wav",
    "Stone Gaze": "voice-pack/audio/stone-gaze-ready.wav",
    "Sunder": "voice-pack/audio/sunder-ready.wav",
    "Supernova": "voice-pack/audio/supernova-ready.wav",
    "Swift Slash": "voice-pack/audio/swift-slash-ready.wav",
    "Tempest Double": "voice-pack/audio/tempest-double-ready.wav",
    "Terrorize": "voice-pack/audio/terrorize-ready.wav",
    "Thundergod's Wrath": "voice-pack/audio/thundergods-wrath-ready.wav",
    "Time Lapse": "voice-pack/audio/time-lapse-ready.wav",
    "Time Walk": "voice-pack/audio/time-walk-ready.wav",
    "Tombstone": "voice-pack/audio/tombstone-ready.wav",
    "Tornado": "voice-pack/audio/tornado-ready.wav",
    "Unleash": "voice-pack/audio/unleash-ready.wav",
    "Upheaval": "voice-pack/audio/upheaval-ready.wav",
    "Vendetta": "voice-pack/audio/vendetta-ready.wav",
    "Wall of Replica": "voice-pack/audio/wall-of-replica-ready.wav",
    "Walrus Punch!": "voice-pack/audio/walrus-punch-ready.wav",
    "Will-O-Wisp": "voice-pack/audio/will-o-wisp-ready.wav",
    "Winter's Curse": "voice-pack/audio/winters-curse-ready.wav",
    "Wukong's Command": "voice-pack/audio/wukongs-command-ready.wav"
  },
  fallback: "voice-pack/audio/cooldown-ready.wav",
};
